{
 "title": "API Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(method, le) (rate(http_request_duration_ms_sum[1m])) / avg by(method) (rate(http_request_duration_ms_count[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"2.*\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"3.*\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"4.*\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"5.*\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "The number of failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"4.*\"}[1m]))",
     "legendFormat": "4xx errors"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{statusCode=~\"5.*\"}[1m]))",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "Number of Valid vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"^2.*|3.*\"}[1m]))",
     "legendFormat": "Valid requests"
    },
    {
     "expr": "sum by (le) (increase(http_request_duration_ms_count{statusCode=~\"^4.*|5.*\"}[1m]))",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"info\"}"
    }
   ]
  }
 ]
}