name: deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup container
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.test.yml"
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: "npm"
          cache-dependency-path: "./was/package-lock.json"
      - run: npm install
        working-directory: was
      - run: npm run test && npm run test:e2e
        working-directory: was

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Load secrets and save to .env.production
        run: aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRETS_MANAGER_NAME }} --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > ./was/src/config/env/.env.production

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./was
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
      - name: Setting Deploy files && Upload to S#
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          mkdir scripts
          touch scripts/deploy.sh
          echo "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY" >> scripts/deploy.sh
          echo "docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> scripts/deploy.sh
          echo "docker container stop was && docker container rm was" >> scripts/deploy.sh
          echo "docker run -d --name was -p ${{ secrets.PORT }}:${{ secrets.PORT }} -v /logs:/app/logs --restart unless-stopped $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> scripts/deploy.sh
          zip -r deploy-$IMAGE_TAG.zip ./scripts appspec.yml
          aws s3 cp --region ${{ secrets.AWS_REGION }} --acl private ./deploy-$IMAGE_TAG.zip s3://${{ secrets.S3_BUCKET }}
      - name: start deploy
        run: |
          aws deploy create-deployment --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOY_GROUP }} \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deploy-$IMAGE_TAG.zip
