name: deploy

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup container
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "../../docker-compose.test.yml"
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: "npm"
          cache-dependency-path: "./was/package-lock.json"
      - run: npm install
        working-directory: was
      - run: npm run test && npm run test:e2e
        working-directory: was
