name: deploy

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: test
        ports:
          - 27010:27017
      redis:
        image: redis
        ports:
          - 6370:6379
      zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_INIT_LIMIT: 5
          ZOOKEEPER_SYNC_LIMIT: 2

    steps:
      - name: Start Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka port: 29090
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: "npm"
          cache-dependency-path: "./was/package-lock.json"
      - run: npm install
        working-directory: was
      - run: npm run test && npm run test:e2e
        working-directory: was
